# Generated by Django 3.0.1 on 2020-03-21 12:54

from django.db import migrations


def add_initial_data(apps, schema_editor):
    Sport = apps.get_model('api', 'Sport')
    Sport.objects.create(name='running')
    Sport.objects.create(name='swimming')
    Sport.objects.create(name='cycling')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
